apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-pv
  # PV에서 namespace 제거
  labels:
    app: elasticsearch
spec:
  # storageClassName 명시적 추가
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/elasticsearch
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-pvc
  namespace: elk
  labels:
    app: elasticsearch
spec:
  # 동일한 storageClassName 사용
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi